#!/usr/bin/env bash
# Local test database for integration tests.
#
#   pnpm test:db:up    # boot local Supabase (Docker) + load supabase-schema.sql + write .env.test
#   pnpm test:db:down  # stop it
#
# Requires: Docker running and the Supabase CLI (https://supabase.com/docs/guides/cli).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

if ! command -v supabase >/dev/null 2>&1; then
  echo "Supabase CLI not found. Install it: https://supabase.com/docs/guides/cli" >&2
  exit 1
fi

cmd="${1:-up}"

case "$cmd" in
  up)
    # `supabase start` needs a config; create one on first run.
    if [ ! -f "supabase/config.toml" ]; then
      echo "==> Initialising local Supabase config"
      supabase init
    fi

    echo "==> Starting local Supabase (Docker)…"
    supabase start

    # Resolve local connection details from the running stack.
    DB_URL="$(supabase status -o env | grep '^DB_URL=' | cut -d= -f2- | tr -d '"')"
    API_URL="$(supabase status -o env | grep '^API_URL=' | cut -d= -f2- | tr -d '"')"
    ANON_KEY="$(supabase status -o env | grep '^ANON_KEY=' | cut -d= -f2- | tr -d '"')"
    SERVICE_KEY="$(supabase status -o env | grep '^SERVICE_ROLE_KEY=' | cut -d= -f2- | tr -d '"')"

    echo "==> Loading schema (supabase-schema.sql)…"
    psql "$DB_URL" -v ON_ERROR_STOP=1 -f supabase-schema.sql >/dev/null

    echo "==> Writing .env.test"
    cat > .env.test <<EOF
# Generated by scripts/test-db.sh — points at the LOCAL Supabase test stack.
NEXT_PUBLIC_SUPABASE_URL=$API_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_KEY
TEST_DATABASE_URL=$DB_URL
EOF

    echo "==> Ready. Run: pnpm test:integration"
    ;;

  down)
    echo "==> Stopping local Supabase…"
    supabase stop
    ;;

  *)
    echo "Usage: scripts/test-db.sh [up|down]" >&2
    exit 1
    ;;
esac
